### PR TITLE
Fix emerge time for packages whose names contains special chars

### PR DESCRIPTION
**Pull request by tusooa**
After fix:
image

Before fix:
image

### CODE REVIEW

**Comment by jonesmz** [comment]
Could you elaborate on what causes the bad behavior. And why the fix is such a large patch?

**Comment by tusooa** [comment]
> Could you elaborate on what causes the bad behavior. And why the fix is such a large patch?

The package name 'gtk+' contains a meta-character for regular expressions. It will not match 'gtk+' literally. Using the Perl sequence `\Q` `\E` will remove the special meaning from these meta-characters.

It is not a large patch. I changed only two lines.

**Comment by jonesmz** [comment]
Ah. You are correct. When I first looked it was a very large patch. But you force pushed and now its only 2 lines of difference.

**Comment by tusooa** [comment]
Maybe it is due to the fact that I was not working from `master` at the beginning.

**Review by jonesmz — APPROVED** [review]

**Comment by jonesmz** [comment]
I've approved the change with the following thoughts:

I don't know that we want (or dont want) to use perl for this package. I personally don't have a problem with it, so I'll defer to another dev to make the tie breaking vote.

I didn't carefully scrutinize your perl code, so I'll trust that you tested it enough to be worth merging.

**Comment by jonesmz** [comment]
Also note that the ebuild in the overlay will need a version bump to pick up your change on end user systems.

**Comment by perkinslr** [comment]
It *looks* like that perl code should work, I do rather dislike per for its inscrutability, but it's not like that grep line was much better.  The whole thing would benefit from a rewrite, but that's the case for lots of the tools, and I don't think this is high priority.

**Pull request merged**
